### ISSUE TITLE
Concurrent requests generates the same text

### ISSUE THREAD

**Issue by ashokgelal** [sgomez/ollama-ai-provider#31]
I've tried generating concurrent requests using the same local model and everytime all the concurrent requests using the same model generate the same text. I've done a quick swap of this with the official [Ollama JS library](https://github.com/ollama/ollama-js) as well as tried using raw fetch call and it works as expected. I wonder if something is cached somewhere or it's because of a singleton somewhere. Using different models works perfectly though.

Edit: I've tried this with both 0.15.2 and 0.16.0

**Comment by ashokgelal** [comment]
To repro:

```ts
import { generateText } from 'ai'
import { ollama, ollama as ollamaType } from 'ollama-ai-provider'

import { buildProgram } from '../tools/command'

async function main(model: Parameters<typeof ollamaType>[0]) {
  saySomethingRandom(model)
  saySomethingRandom(model)
}

function saySomethingRandom(model: Parameters<typeof ollamaType>[0]) {
  generateText({
    messages: [
      {
        content: 'Say something very random',
        role: 'user',
      },
    ],
    model: ollama(model),
  }).then((result) => {
    console.log(result.text)
  })
}

buildProgram('qwen2.5:7b', main).catch(console.error)
```


And this is what I get:

![CleanShot 2024-11-03 at 13 49 30@2x](https://github.com/user-attachments/assets/aeac9912-5b6f-4cee-baff-35f166049ea6)

**Comment by sgomez** [comment]
Hi @ashokgelal,

It seems that the Vercel SDK AI library always sets the temperature to 0, and Ollama uses a seed when this happens. So, the issue isn’t with concurrent requests—it occurs consistently because of the seed. I’ll need to determine whether this is a bug with Ollama or the Vercel SDK and report it to the appropriate project.

I can’t remove the default temperature setting because there’s no way to tell if 0 is a custom value or just the default.

You can do a workaround adding a random seed each time you call generateText.

**Comment by sgomez** [comment]
Yes, a temperature of 0 is the default value in the Vercel SDK AI, and this behavior is documented, so it’s not a bug—it’s the intended default.

If you want to use Ollama’s default temperature, set the temperature option to 0.8.

https://github.com/ollama/ollama/blob/main/api/types.go#L592
