### ISSUE TITLE
No results from model with tools config

### ISSUE THREAD

**Issue by dprosper** [sgomez/ollama-ai-provider#34]
Opening here based on feedback provided here: https://github.com/vercel/ai/issues/3957#issuecomment-2514105970

**Describe the bug**
### Description

Using the guide: https://sdk.vercel.ai/docs/guides/rag-chatbot

Follow the steps above to build the OpenAI example to the end and validate that it works. 

Replace openai with ollama in the api/chat/route.ts 

```sh
import { createOllama } from 'ollama-ai-provider';
....
const ollama = createOllama({
  baseURL: 'http://localhost:11434/api',
})

.....

 const result = streamText({
    model: ollama(`llama3.2:latest`), 
    messages,

....
```

If you remove the tools config in the streamText you can see an output from the model, once you add the tools config back you get no response from the model.

### AI provider

ollama-ai-provider 1.0.0 and ai 4.0.10

**Comment by sgomez** [comment]
[Ollama does not support streaming tools](https://github.com/ollama/ollama/blob/main/docs/api.md#parameters-1), so there is nothing we can do. You can only use generateText or generateObjects.

Streaming support is an experimental feature of this provider and works only with certain models. This is because we can detect when the stream sends an object, and the provider intercepts it to send it partially through the stream. However, this is merely a simulation.
